### ISSUE TITLE
Add support for variable types

### ISSUE THREAD

**Issue by franz-josef-kaiser** [barundel/terraform-aws-organizations#2]
As of now, no `variable` defined [inside `variables.tf`](https://github.com/barundel/terraform-aws-organizations/blob/dc07fad19f39f08b9948177130939fa72d27b5b7/variables.tf) supports `type`s.

Reasoning: Adding types for single `variable` definitions helps to catch errors early on. For e.g. adding a `string` when a `list` is expected, returns a clear error message that helps fixing the problem in no time.

```diff
# variables.tf
variable "feature_set" {
  default = "ALL"
+ type = string
  description = "Specify ALL (default) or CONSOLIDATED_BILLING"
}
```

Adding the type results in the following error when a `list` was used instead of the correct `string` type:
```python
Error: Invalid default value for variable

  on ../../../modules/aws-org/vars.tf line 14, in variable "feature_set":
  14:   default = "ALL"

This default value is not compatible with the variable's type constraint: list
of string required.
```

**Comment by barundel** [comment]
thanks @franz-josef-kaiser ill take a look at these this week.
